# Generated by Django 2.1.5 on 2019-01-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190124_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_html',
            field=models.TextField(blank=True, verbose_name='태그가 HTML화된 댓글 내용'),
        ),
    ]
